// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/avianlabs/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func injectBar() (*Bar, func()) {
	foo, cleanup := SingletonProvideFoo()
	bar := provideBar(
		foo,
	)
	return bar, func() {
		cleanup()
	}
}
