// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/avianlabs/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func injectBar(cfg Config, opts ...string) (*Bar, func(), error) {
	foo, cleanup, err := SingletonProvideFoo(
		cfg,
		opts...,
	)
	if err != nil {
		return nil, nil, err
	}
	bar := provideBar(
		foo,
	)
	return bar, func() {
		cleanup()
	}, nil
}

func injectBaz() (*Baz, func(), error) {
	baz, cleanup, err := SingletonProvideBaz()
	if err != nil {
		return nil, nil, err
	}
	return baz, func() {
		cleanup()
	}, nil
}
