// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/avianlabs/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"sync"
)

// Singleton wrappers:

var (
	singletonProvideFooMu      sync.Mutex
	singletonProvideFooRefs    int
	singletonProvideFooValue   *Foo
	singletonProvideFooCleanup func()
)

// SingletonProvideFoo memoizes provideFoo. It is generated by Wire because
// provideFoo is wrapped in wire.Singleton in this package.
func SingletonProvideFoo() (*Foo, func()) {
	singletonProvideFooMu.Lock()
	defer singletonProvideFooMu.Unlock()
	if singletonProvideFooRefs == 0 {
		singletonProvideFooValue, singletonProvideFooCleanup = provideFoo()
	}
	singletonProvideFooRefs++
	return singletonProvideFooValue, releaseSingletonProvideFoo
}

func releaseSingletonProvideFoo() {
	singletonProvideFooMu.Lock()
	defer singletonProvideFooMu.Unlock()
	if singletonProvideFooRefs == 0 {
		return
	}
	singletonProvideFooRefs--
	if singletonProvideFooRefs == 0 {
		if singletonProvideFooCleanup != nil {
			singletonProvideFooCleanup()
		}
		singletonProvideFooValue = nil
		singletonProvideFooCleanup = nil
	}
}
