// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/avianlabs/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"sync"
)

// Singleton wrappers:

var (
	singletonProvideBazMu      sync.Mutex
	singletonProvideBazRefs    int
	singletonProvideBazValue   *Baz
	singletonProvideBazCleanup func()
	singletonProvideBazErr     error
)

// SingletonProvideBaz memoizes provideBaz. It is generated by Wire because
// provideBaz is wrapped in wire.Singleton in this package.
func SingletonProvideBaz() (*Baz, func(), error) {
	singletonProvideBazMu.Lock()
	defer singletonProvideBazMu.Unlock()
	if singletonProvideBazErr != nil {
		return nil, nil, singletonProvideBazErr
	}
	if singletonProvideBazRefs == 0 {
		singletonProvideBazValue, singletonProvideBazCleanup, singletonProvideBazErr = provideBaz()
		if singletonProvideBazErr != nil {
			return nil, nil, singletonProvideBazErr
		}
	}
	singletonProvideBazRefs++
	return singletonProvideBazValue, releaseSingletonProvideBaz, nil
}

func releaseSingletonProvideBaz() {
	singletonProvideBazMu.Lock()
	defer singletonProvideBazMu.Unlock()
	if singletonProvideBazRefs == 0 {
		return
	}
	singletonProvideBazRefs--
	if singletonProvideBazRefs == 0 {
		if singletonProvideBazCleanup != nil {
			singletonProvideBazCleanup()
		}
		singletonProvideBazValue = nil
		singletonProvideBazCleanup = nil
	}
}

var (
	singletonProvideFooMu      sync.Mutex
	singletonProvideFooRefs    int
	singletonProvideFooValue   *Foo
	singletonProvideFooCleanup func()
	singletonProvideFooErr     error
)

// SingletonProvideFoo memoizes provideFoo. It is generated by Wire because
// provideFoo is wrapped in wire.Singleton in this package.
func SingletonProvideFoo(config Config, arg1 ...string) (*Foo, func(), error) {
	singletonProvideFooMu.Lock()
	defer singletonProvideFooMu.Unlock()
	if singletonProvideFooErr != nil {
		return nil, nil, singletonProvideFooErr
	}
	if singletonProvideFooRefs == 0 {
		singletonProvideFooValue, singletonProvideFooCleanup, singletonProvideFooErr = provideFoo(config, arg1...)
		if singletonProvideFooErr != nil {
			return nil, nil, singletonProvideFooErr
		}
	}
	singletonProvideFooRefs++
	return singletonProvideFooValue, releaseSingletonProvideFoo, nil
}

func releaseSingletonProvideFoo() {
	singletonProvideFooMu.Lock()
	defer singletonProvideFooMu.Unlock()
	if singletonProvideFooRefs == 0 {
		return
	}
	singletonProvideFooRefs--
	if singletonProvideFooRefs == 0 {
		if singletonProvideFooCleanup != nil {
			singletonProvideFooCleanup()
		}
		singletonProvideFooValue = nil
		singletonProvideFooCleanup = nil
	}
}
