// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/avianlabs/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"sync"
)

// Injectors from wire.go:

func injectFooBar() *FooBar {
	foo := _wireFooSingleton()
	fooBar := provideFooBar(
		foo,
	)
	return fooBar
}

func injectFooBaz() *FooBaz {
	foo := _wireFooSingleton()
	fooBaz := provideFooBaz(
		foo,
	)
	return fooBaz
}

// Singleton wrappers:

var (
	_wireFooSingletonOnce  sync.Once
	_wireFooSingletonValue *Foo
)

func _wireFooSingleton() *Foo {
	_wireFooSingletonOnce.Do(func() {
		_wireFooSingletonValue = provideFoo()
	})
	return _wireFooSingletonValue
}
