// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/avianlabs/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func injectFooBar() *FooBar {
	foo := SingletonProvideFoo()
	fooBar := provideFooBar(
		foo,
	)
	return fooBar
}

func injectFooBaz() *FooBaz {
	foo := SingletonProvideFoo()
	fooBaz := provideFooBaz(
		foo,
	)
	return fooBaz
}
