// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/avianlabs/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"sync"
)

// Singleton wrappers:

var (
	singletonProvideFooOnce  sync.Once
	singletonProvideFooValue *Foo
)

// SingletonProvideFoo memoizes provideFoo. It is generated by Wire because
// provideFoo is wrapped in wire.Singleton in this package.
func SingletonProvideFoo() *Foo {
	singletonProvideFooOnce.Do(func() {
		singletonProvideFooValue = provideFoo()
	})
	return singletonProvideFooValue
}
