// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/avianlabs/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inj1

import (
	"example.com/bar"
)

// Injectors from wire.go:

func Foo() *bar.Foo {
	foo := bar.SingletonNewFoo()
	return foo
}

func Client(cfg bar.Config) *bar.Client {
	foo := bar.SingletonNewFoo()
	client := bar.SingletonNewClient(
		cfg,
		foo,
	)
	return client
}
