// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/avianlabs/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bar

import (
	"sync"
)

// Singleton wrappers:

var (
	singletonNewClientOnce  sync.Once
	singletonNewClientValue *Client
)

// SingletonNewClient memoizes NewClient. It is generated by Wire because
// NewClient is wrapped in wire.Singleton in this package.
func SingletonNewClient(config Config, foo *Foo) *Client {
	singletonNewClientOnce.Do(func() {
		singletonNewClientValue = NewClient(config, foo)
	})
	return singletonNewClientValue
}

var (
	singletonNewFooOnce  sync.Once
	singletonNewFooValue *Foo
)

// SingletonNewFoo memoizes NewFoo. It is generated by Wire because
// NewFoo is wrapped in wire.Singleton in this package.
func SingletonNewFoo() *Foo {
	singletonNewFooOnce.Do(func() {
		singletonNewFooValue = NewFoo()
	})
	return singletonNewFooValue
}
