// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/avianlabs/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func injectFoo() (*Foo, error) {
	foo, err := SingletonProvideFoo()
	if err != nil {
		return nil, err
	}
	return foo, nil
}
