// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/avianlabs/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"sync"
)

// Injectors from wire.go:

func injectFoo() (*Foo, error) {
	foo, err := _wireFooSingleton()
	if err != nil {
		return nil, err
	}
	return foo, nil
}

// Singleton wrappers:

var (
	_wireFooSingletonOnce  sync.Once
	_wireFooSingletonValue *Foo
	_wireFooSingletonErr   error
)

func _wireFooSingleton() (*Foo, error) {
	_wireFooSingletonOnce.Do(func() {
		_wireFooSingletonValue, _wireFooSingletonErr = provideFoo()
	})
	return _wireFooSingletonValue, _wireFooSingletonErr
}
